"""baseline schema

Revision ID: 5dfecc15823e
Revises: 
Create Date: 2026-07-08 15:42:00.194178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dfecc15823e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name_ro', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_slug'), 'cities', ['slug'], unique=True)
    op.create_table('events',
    sa.Column('actor_type', sa.Enum('system', 'user', 'staff', 'admin', name='actortype'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_created_at', 'events', ['created_at'], unique=False)
    op.create_index('ix_events_entity', 'events', ['entity_type', 'entity_id'], unique=False)
    op.create_table('magic_link_tokens',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_link_tokens_email'), 'magic_link_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_magic_link_tokens_token_hash'), 'magic_link_tokens', ['token_hash'], unique=True)
    op.create_table('price_list',
    sa.Column('item_type', sa.Enum('bag', 'trolley', 'oversized', name='itemtype'), nullable=False),
    sa.Column('price_ron', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_list_item_type'), 'price_list', ['item_type'], unique=False)
    op.create_index(op.f('ix_price_list_valid_from'), 'price_list', ['valid_from'], unique=False)
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.Enum('ro', 'en', name='locale'), nullable=False),
    sa.Column('marketing_consent', sa.Boolean(), nullable=False),
    sa.Column('marketing_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discount_pct', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('admin_password_hash', sa.String(length=255), nullable=True),
    sa.Column('admin_totp_secret', sa.String(length=64), nullable=True),
    sa.Column('admin_totp_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('locations',
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('description_ro', sa.String(length=4000), nullable=True),
    sa.Column('description_en', sa.String(length=4000), nullable=True),
    sa.Column('photos', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'delisted', name='locationstatus'), nullable=False),
    sa.Column('strike_count', sa.SmallInteger(), nullable=False),
    sa.Column('revenue_share_pct', sa.SmallInteger(), nullable=False),
    sa.Column('utm_code', sa.String(length=32), nullable=False),
    sa.Column('google_maps_url', sa.String(length=1000), nullable=True),
    sa.Column('google_review_url', sa.String(length=1000), nullable=True),
    sa.Column('created_by_admin', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['created_by_admin'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_city_id'), 'locations', ['city_id'], unique=False)
    op.create_index(op.f('ix_locations_slug'), 'locations', ['slug'], unique=True)
    op.create_index(op.f('ix_locations_status'), 'locations', ['status'], unique=False)
    op.create_index(op.f('ix_locations_utm_code'), 'locations', ['utm_code'], unique=True)
    op.create_table('bookings',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_email', postgresql.CITEXT(), nullable=False),
    sa.Column('guest_phone', sa.String(length=32), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('storage_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending_payment', 'confirmed', 'stored', 'released', 'closed', 'expired', 'cancelled', 'no_show', name='bookingstatus'), nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('utm_campaign', sa.String(length=128), nullable=True),
    sa.Column('utm_source', sa.String(length=128), nullable=True),
    sa.Column('utm_medium', sa.String(length=128), nullable=True),
    sa.Column('locale', sa.Enum('ro', 'en', name='locale'), nullable=False),
    sa.Column('revenue_share_pct_snapshot', sa.Integer(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('traveler_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kept_overnight', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_code'), 'bookings', ['code'], unique=True)
    op.create_index(op.f('ix_bookings_guest_email'), 'bookings', ['guest_email'], unique=False)
    op.create_index(op.f('ix_bookings_location_id'), 'bookings', ['location_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_storage_date'), 'bookings', ['storage_date'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('location_hours',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'weekday', name='uq_location_hours_day')
    )
    op.create_index(op.f('ix_location_hours_location_id'), 'location_hours', ['location_id'], unique=False)
    op.create_table('location_item_types',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('bag', 'trolley', 'oversized', name='itemtype'), nullable=False),
    sa.Column('daily_capacity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'item_type', name='uq_location_item_type')
    )
    op.create_index(op.f('ix_location_item_types_location_id'), 'location_item_types', ['location_id'], unique=False)
    op.create_table('location_login_tokens',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_pin_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_login_tokens_location_id'), 'location_login_tokens', ['location_id'], unique=False)
    op.create_index(op.f('ix_location_login_tokens_token_hash'), 'location_login_tokens', ['token_hash'], unique=True)
    op.create_table('location_overrides',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'date', name='uq_location_override_date')
    )
    op.create_index(op.f('ix_location_overrides_location_id'), 'location_overrides', ['location_id'], unique=False)
    op.create_table('settlements',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('totals_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_report_r2_key', sa.String(length=500), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlements_location_id'), 'settlements', ['location_id'], unique=False)
    op.create_index(op.f('ix_settlements_period'), 'settlements', ['period'], unique=False)
    op.create_table('staff_members',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('staff', 'owner', name='staffrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_pin_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_members_location_id'), 'staff_members', ['location_id'], unique=False)
    op.create_table('bag_photos',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('r2_key', sa.String(length=500), nullable=False),
    sa.Column('taken_by_staff_id', sa.UUID(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['taken_by_staff_id'], ['staff_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bag_photos_booking_id'), 'bag_photos', ['booking_id'], unique=False)
    op.create_table('booking_items',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('bag', 'trolley', 'oversized', name='itemtype'), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_items_booking_id'), 'booking_items', ['booking_id'], unique=False)
    op.create_table('booking_qr_tokens',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_qr_tokens_booking_id'), 'booking_qr_tokens', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_qr_tokens_token_hash'), 'booking_qr_tokens', ['token_hash'], unique=True)
    op.create_table('payments',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=False),
    sa.Column('payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'refunded', 'partially_refunded', name='paymentstatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_intent_id'), 'payments', ['payment_intent_id'], unique=False)
    op.create_index(op.f('ix_payments_stripe_checkout_session_id'), 'payments', ['stripe_checkout_session_id'], unique=True)
    op.create_table('promo_codes',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('amount_ron', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pct', sa.Integer(), nullable=True),
    sa.Column('single_use', sa.Boolean(), nullable=False),
    sa.Column('issued_to_email', postgresql.CITEXT(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_on_booking_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['redeemed_on_booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.create_index(op.f('ix_promo_codes_issued_to_email'), 'promo_codes', ['issued_to_email'], unique=False)
    op.create_table('refunds',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.Enum('traveler_cancel', 'host_closed', 'system_unstored', 'admin_manual', 'goodwill', name='refundreason'), nullable=False),
    sa.Column('stripe_refund_id', sa.String(length=255), nullable=True),
    sa.Column('initiated_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_booking_id'), 'refunds', ['booking_id'], unique=False)
    op.create_index(op.f('ix_refunds_stripe_refund_id'), 'refunds', ['stripe_refund_id'], unique=False)
    op.create_table('strikes',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strikes_location_id'), 'strikes', ['location_id'], unique=False)
    op.create_table('tickets',
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('open', 'pending', 'closed', name='ticketstatus'), nullable=False),
    sa.Column('reply_token_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_booking_id'), 'tickets', ['booking_id'], unique=False)
    op.create_index(op.f('ix_tickets_email'), 'tickets', ['email'], unique=False)
    op.create_index(op.f('ix_tickets_reply_token_hash'), 'tickets', ['reply_token_hash'], unique=True)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_table('email_log',
    sa.Column('to', postgresql.CITEXT(), nullable=False),
    sa.Column('template', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'delivered', 'bounced', 'failed', name='emailstatus'), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('related_booking_id', sa.UUID(), nullable=True),
    sa.Column('related_ticket_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['related_ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_log_to'), 'email_log', ['to'], unique=False)
    op.create_table('ticket_messages',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.Enum('traveler', 'admin', name='ticketauthor'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages')
    op.drop_table('ticket_messages')
    op.drop_index(op.f('ix_email_log_to'), table_name='email_log')
    op.drop_table('email_log')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_reply_token_hash'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_email'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_booking_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_strikes_location_id'), table_name='strikes')
    op.drop_table('strikes')
    op.drop_index(op.f('ix_refunds_stripe_refund_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_booking_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_promo_codes_issued_to_email'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_index(op.f('ix_payments_stripe_checkout_session_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_intent_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_booking_qr_tokens_token_hash'), table_name='booking_qr_tokens')
    op.drop_index(op.f('ix_booking_qr_tokens_booking_id'), table_name='booking_qr_tokens')
    op.drop_table('booking_qr_tokens')
    op.drop_index(op.f('ix_booking_items_booking_id'), table_name='booking_items')
    op.drop_table('booking_items')
    op.drop_index(op.f('ix_bag_photos_booking_id'), table_name='bag_photos')
    op.drop_table('bag_photos')
    op.drop_index(op.f('ix_staff_members_location_id'), table_name='staff_members')
    op.drop_table('staff_members')
    op.drop_index(op.f('ix_settlements_period'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_location_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_location_overrides_location_id'), table_name='location_overrides')
    op.drop_table('location_overrides')
    op.drop_index(op.f('ix_location_login_tokens_token_hash'), table_name='location_login_tokens')
    op.drop_index(op.f('ix_location_login_tokens_location_id'), table_name='location_login_tokens')
    op.drop_table('location_login_tokens')
    op.drop_index(op.f('ix_location_item_types_location_id'), table_name='location_item_types')
    op.drop_table('location_item_types')
    op.drop_index(op.f('ix_location_hours_location_id'), table_name='location_hours')
    op.drop_table('location_hours')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_storage_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_location_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_guest_email'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_code'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_locations_utm_code'), table_name='locations')
    op.drop_index(op.f('ix_locations_status'), table_name='locations')
    op.drop_index(op.f('ix_locations_slug'), table_name='locations')
    op.drop_index(op.f('ix_locations_city_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_price_list_valid_from'), table_name='price_list')
    op.drop_index(op.f('ix_price_list_item_type'), table_name='price_list')
    op.drop_table('price_list')
    op.drop_index(op.f('ix_magic_link_tokens_token_hash'), table_name='magic_link_tokens')
    op.drop_index(op.f('ix_magic_link_tokens_email'), table_name='magic_link_tokens')
    op.drop_table('magic_link_tokens')
    op.drop_index('ix_events_entity', table_name='events')
    op.drop_index('ix_events_created_at', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_cities_slug'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
    # autogenerate doesn't drop the ENUM types it created for us
    for enum_name in (
        'actortype', 'bookingstatus', 'emailstatus', 'itemtype', 'locale',
        'locationstatus', 'paymentstatus', 'refundreason', 'staffrole',
        'ticketauthor', 'ticketstatus',
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    op.execute("DROP EXTENSION IF EXISTS citext")
